---
- name: Install Docker
  hosts: postgresql

  tasks:
  - name: Install Docker
    become: true
    ansible.builtin.yum:
      name: docker
      state: present
  - name: Run Docker
    become: true
    ansible.builtin.service:
      name: docker
      state: started
      enabled: true
  - name: Install Docker-compose
    ansible.builtin.shell: |
      sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
